version: "3"

services:
  postgres:
    image: postgres:latest
    ports:
      - 5829:5829
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=o8BzJi2r4br7cH9gkfBp
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=mesgel@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - 15432:80
