version: "3"

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=week13
      - POSTGRES_USER=prismaweek13
      - POSTGRES_PASSWORD=rahasia
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=mesgel@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - 15432:80
