# fly.toml app configuration file generated for prisma13 on 2023-05-06T15:24:15+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prisma13"
primary_region = "sin"

[env]
  PORT = "8080"
  DATABASE_URL="postgres://postgres:0BgXs2zdhnz2BgT@prismamesel.flycast:5432/week13fly?schema=public"
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true